### ISSUE TITLE
Did I input the wrong argument?

### ISSUE THREAD

**Issue by OkazakiNaoki** [DarkStarSword/3d-fixes#1]
I saw your reply in DerPopo/UABE which is talking about how to extract shader of Unity.
I just run the unity_asset_extractor.py with the asset file I want to see and then show up error.
`  File "unity_asset_extractor.py", line 633, in <module>`
`    main()`
`  File "unity_asset_extractor.py", line 628, in main`
`    analyse(open(file, 'rb'))`
`  File "unity_asset_extractor.py", line 592, in analyse`
`    assert(os.fstat(file.fileno()).st_size == file_len)`
`AssertionError`

Feed asset file to unity_asset_extractor.py and get shader.decompressed right?
Then feed shader.decompressed to extract_unity55_shaders.py.
Did I misunderstand anything?

Also try unity_asset_bundle_extractor.py, still get the error.
`  File "unity_asset_bundle_extractor.py", line 228, in <module>`
`    main()`
`  File "unity_asset_bundle_extractor.py", line 223, in main`
`    analyse(open(file, 'rb'))`
`  File "unity_asset_bundle_extractor.py", line 176, in analyse`
`    assert(data_header.read(16) == b'\0' * 16)`
`AttributeError: 'bytes' object has no attribute 'read'`

Yup... by the way it's 5.6 version asset.

**Comment by OkazakiNaoki** [comment]
Ok. I did it correctly now.
I just want to see if shader is still readable after decompile/disassemble.
So...it is basically no way to get shader source.
Thank you.

**Comment by DarkStarSword** [comment]
If it's an OpenGL shader you will get something close - not the exact Cg source from Unity, but a translation of that to GLSL, which is pretty close.

But DirectX shaders are compiled to bytecode, so will be much the same as disassembling/decompiling a C program - it's still possible to examine them and work out what they are doing, but much harder than reading source.

If you're looking for the source for any standard Unity shaders, don't forget that they are available from the Unity download page under "Older versions of Unity" -> "Downloads (Win)" -> Built in Shaders.

**Comment by OkazakiNaoki** [comment]
Umm...then do you have GLSL shader asset sample? (Or I just need to change Unity build option and it will come out with GLSL version?)
I would like to see how close it is.

The reason why I curious is that I saw a reply at Unity forum which said :
"As nvidia is not supporting CG anymore, latest unity versions actually compile shaders using HLSL compiler and transform the resulting bytecode to GLSL."

Then does it mean that the compile order is Cg->HLSL bytecode->GLSL ?
How come GLSL code is more readable than HLSL since it's transformed from HLSL bytecode.
Or that reply is old information and no longer correct?

**Comment by DarkStarSword** [comment]
I haven't looked at an OpenGL shader from Unity in ages, but based on this, I'd say you're probably right - although this is clearly translated from bytecode *before* the reflection information has been stripped. This is from Hidden/Internal-DeferredReflections:

    #define VERTEX
    #ifdef VERTEX
    #version 150
    #extension GL_ARB_explicit_attrib_location : require
    #extension GL_ARB_shader_bit_encoding : enable
    
    uniform 	vec4 _ProjectionParams;
    uniform 	vec4 hlslcc_mtx4x4unity_ObjectToWorld[4];
    uniform 	vec4 hlslcc_mtx4x4unity_MatrixV[4];
    uniform 	vec4 hlslcc_mtx4x4unity_MatrixVP[4];
    uniform 	float _LightAsQuad;
    in  vec4 in_POSITION0;
    in  vec3 in_NORMAL0;
    out vec4 vs_TEXCOORD0;
    out vec3 vs_TEXCOORD1;
    vec4 u_xlat0;
    vec4 u_xlat1;
    vec4 u_xlat2;
    void main()
    {
        u_xlat0 = in_POSITION0.yyyy * hlslcc_mtx4x4unity_ObjectToWorld[1];
        u_xlat0 = hlslcc_mtx4x4unity_ObjectToWorld[0] * in_POSITION0.xxxx + u_xlat0;
        u_xlat0 = hlslcc_mtx4x4unity_ObjectToWorld[2] * in_POSITION0.zzzz + u_xlat0;
        u_xlat0 = u_xlat0 + hlslcc_mtx4x4unity_ObjectToWorld[3];
        u_xlat1 = u_xlat0.yyyy * hlslcc_mtx4x4unity_MatrixVP[1];
        u_xlat1 = hlslcc_mtx4x4unity_MatrixVP[0] * u_xlat0.xxxx + u_xlat1;
        u_xlat1 = hlslcc_mtx4x4unity_MatrixVP[2] * u_xlat0.zzzz + u_xlat1;
        u_xlat1 = hlslcc_mtx4x4unity_MatrixVP[3] * u_xlat0.wwww + u_xlat1;
        gl_Position = u_xlat1;
        u_xlat1.y = u_xlat1.y * _ProjectionParams.x;
        u_xlat2.xzw = u_xlat1.xwy * vec3(0.5, 0.5, 0.5);
        vs_TEXCOORD0.zw = u_xlat1.zw;
        vs_TEXCOORD0.xy = u_xlat2.zz + u_xlat2.xw;
        u_xlat1.xyz = u_xlat0.yyy * hlslcc_mtx4x4unity_MatrixV[1].xyz;
        u_xlat1.xyz = hlslcc_mtx4x4unity_MatrixV[0].xyz * u_xlat0.xxx + u_xlat1.xyz;
        u_xlat0.xyz = hlslcc_mtx4x4unity_MatrixV[2].xyz * u_xlat0.zzz + u_xlat1.xyz;
        u_xlat0.xyz = hlslcc_mtx4x4unity_MatrixV[3].xyz * u_xlat0.www + u_xlat0.xyz;
        u_xlat1.xyz = u_xlat0.xyz * vec3(-1.0, -1.0, 1.0);
        u_xlat0.xyz = (-u_xlat0.xyz) * vec3(-1.0, -1.0, 1.0) + in_NORMAL0.xyz;
        vs_TEXCOORD1.xyz = vec3(_LightAsQuad) * u_xlat0.xyz + u_xlat1.xyz;
        return;
    }
    
    #endif
    #ifdef FRAGMENT
    #version 150
    #extension GL_ARB_explicit_attrib_location : require
    #extension GL_ARB_shader_bit_encoding : enable
    
    uniform 	vec3 _WorldSpaceCameraPos;
    uniform 	vec4 _ProjectionParams;
    uniform 	vec4 _ZBufferParams;
    uniform 	vec4 hlslcc_mtx4x4unity_CameraToWorld[4];
    uniform 	vec4 unity_SpecCube0_BoxMax;
    uniform 	vec4 unity_SpecCube0_BoxMin;
    ...

That looks pretty similar to 3DMigoto's decompiler output from when reflection information is present - you can see that the matrix mul() has been broken up into individual multiplications and additions for example.

I definitely remember the GLSL in older versions of Unity was much closer to the Cg source code, but our focus has mostly been on the DX shaders so I haven't paid a huge amount of attention to when that changed.

**Comment by OkazakiNaoki** [comment]
I tried 2017 version today and try to make some example assets file to extract OpenGL shader code.
And then I get pretty much the same result you paste.
What I don't understand is that why so many output? pixel and vertex 36 each?

Most important...I don't see any logic in those codes.
I guess Unity wins?

**Comment by DarkStarSword** [comment]
>  What I don't understand is that why so many output? pixel and vertex 36 each?

The pre-processor directives in the Cg source code lead to many permutations of different shaders - The "Keywords" attribute in the headers tells you which permutation of pre-processor defines were active for that specific shader. 36 is nothing - it is not uncommon for a single Unity shader to explode into hundreds of actual shaders, and in some games the "Standard" and "Hidden/Post FX/Uber Shader" explode into the thousands.

For the OpenGL shaders you should note that the fp directory is actually synthesized by the extraction tools - it contains the same shaders as the vp directory, but with #define FRAGMENT at the top instead of #define VERTEX, and the hashes in the filenames will be different as a result.

> Most important...I don't see any logic in those codes.

It is there - I analyse these all the time, but it is a lot harder to follow than just reading Cg - you really have to be familiar with assembly to be able to decipher these (e.g. you should be able to easily spot three row-major matrix multiplications in the shader I pasted above), and best if you can go in and experiment with changing them to observe what happens:
- For DX11 shaders use 3DMigoto for live experiments, removing the nvapi.dll if you are using AMD.
- OpenGL shaders might still work with Helifax' OpenGL 3D Vision Wrapper, but I don't have much experience with it, no idea if it will work if you don't have 3D Vision and if there have been any changes to how Unity munges the shaders in the last couple of years there is a possibility the hashes may no longer match - OpenGL was only ever added as an experiment for these scripts, though Helifax was able get a Unity game running in OpenGL working with 3D Vision, so it was a successful experiment.
