### ISSUE TITLE
Vertex buffer expansion on export

### ISSUE THREAD

**Issue by eArmada8** [DarkStarSword/3d-fixes#35]
Hi,

I noticed that when I import a vertex buffer, then export it again, the size of the vertex buffer is enlarged.  This might be desired behavior, I do not know, so I thought I would ask.

[Looking at this mesh](https://github.com/user-attachments/files/16483239/shadow_mesh.zip), for example; the original mesh has 2721 vertices, and when imported into Blender, it still has 2721 vertices.  The old stable script would output a mesh with 2721 vertices, but the current commit outputs 2786 vertices.  The appearance of the mesh seems to be the same.

The first triangle to show a difference is triangle 325, which is at offset 0x3CA in the index buffer.  163,168,167 has been changed to 163,168,169.  Vertex 167 and 169 are *almost* identical, except the tangent vector is now different.

This does not happen with most meshes, but I have found more than a few.  So it seems that the script is determining that some vertices need to be duplicated with differing tangent vectors?  Is this desired behavior?

Thanks for looking into this!

**Comment by DarkStarSword** [comment]
Sorry I haven't had a chance to look at this - can you confirm that you used the same version of Blender for both tests? How old was the "old stable" version of the script you used? There was a change to how normals were imported recently for Blender 4.1 compatibility that might have impacted this, though if it was a much older version of the script there could have been other changes in the interim.

**Comment by StarBobis** [comment]
> Hi,
> 
> I noticed that when I import a vertex buffer, then export it again, the size of the vertex buffer is enlarged. This might be desired behavior, I do not know, so I thought I would ask.
> 
> [Looking at this mesh](https://github.com/user-attachments/files/16483239/shadow_mesh.zip), for example; the original mesh has 2721 vertices, and when imported into Blender, it still has 2721 vertices. The old stable script would output a mesh with 2721 vertices, but the current commit outputs 2786 vertices. The appearance of the mesh seems to be the same.
> 
> The first triangle to show a difference is triangle 325, which is at offset 0x3CA in the index buffer. 163,168,167 has been changed to 163,168,169. Vertex 167 and 169 are _almost_ identical, except the tangent vector is now different.
> 
> This does not happen with most meshes, but I have found more than a few. So it seems that the script is determining that some vertices need to be duplicated with differing tangent vectors? Is this desired behavior?
> 
> Thanks for looking into this!

Sorry to interrupt you, but I have a idea to share, only for reference, hope it can provide some helps:

This is a normal situation because blender_3dmigoto.py use ”class HashableVertex“ to calculate vertices,
but every point which contains TANGENT value is different in loop_vertex,each point from mesh.loops have more than one TANGENT value if it's calculated by blender's method.

see blender_vertex_to_3dmigoto_vertex function: 
        elif elem.name.startswith('TANGENT'):
            # DOAXVV has +1/-1 in the 4th component. Not positive what this is,
            # but guessing maybe the bitangent sign? Not even sure it is used...
            # FIXME: Other games
            vertex[elem.name] = elem.pad(list(blender_loop_vertex.tangent), blender_loop_vertex.bitangent_sign)

the core reason is blender_loop_vertex is come from mesh.loops, in Blender , vertex in mesh.loops have more than one TANGENT value in one point after mesh.calc_tangents(), so after hashable calculate ,it generate more vertices than before.

To solve this problem, here is my simple way to solve it, add a extra process to make sure one vertex only use single one TANGENT value before calculate index_vertex:
![image](https://github.com/user-attachments/assets/44e45de3-63f8-4101-be96-80cf234f7c45)

like this:

            # if "POSITION" in vertex and "NORMAL" in vertex and "TANGENT" in vertex and "BLENDINDICES" in vertex and "TEXCOORD" in vertex:
            #     if tuple(vertex["POSITION"] + vertex["NORMAL"] + vertex["BLENDINDICES"] + vertex["TEXCOORD"]  ) in unique_position_vertices:
            #         tangent_var = unique_position_vertices[tuple(vertex["POSITION"] + vertex["NORMAL"] + vertex["BLENDINDICES"] + vertex["TEXCOORD"] )]
            #         vertex["TANGENT"] = tangent_var
            #     else:
            #         tangent_var = vertex["TANGENT"]
            #         unique_position_vertices[tuple(vertex["POSITION"] + vertex["NORMAL"] + vertex["BLENDINDICES"] + vertex["TEXCOORD"] )] = tangent_var
            #         vertex["TANGENT"] = tangent_var
            

This is a common problem when you can't break vertex number limit in d3d11 buffer replace game modding.
And I hope if there can be a average calculate for TANGENT value will be better for only save a single one of all TANGENT in one point.

(I guess you may meet some problem for can't change buffer size so have to use original vertex number? if you can provide the game i may can help to test to break it.)

more code can see here,I meet this problem a few month ago and solved this extra vertex count problem:
https://github.com/StarBobis/MMT-Blender-Plugin/blob/main/MMT_4_2LTS/migoto_format.py
it also have a right click menu button to show original vertex number and current calculated index_vertex number.

i'm noob too but want to provide some help, if there is something wrong welcome to correct me.

**Comment by eArmada8** [comment]
@DarkStarSword - sorry, I was using [this commit](https://github.com/DarkStarSword/3d-fixes/commit/c6daca90d64b0fb53f2ebf70806e539b8007d328), which was the last one before you started the updates to support segmented vertex buffers, on Blender 3.6 LTS.  I noticed this behavior with the current commit, on Blender 4.2 LTS.

**Comment by leotorrez** [comment]
> This does not happen with most meshes, but I have found more than a few. So it seems that the script is determining that some vertices need to be duplicated with differing tangent vectors? Is this desired behavior?

On import the tangent of a buffer is discarded by default in favor of recalculating on export, said calculation is done by blender API entirely.

If your game uses custom tangents and not one calculated from normals in the same algo as blender would, you might get different tangents. Hence the vert count has potential to change cause vertex uniqueness is tampered with by this process.

You could try importing the tangent with use of semantic remap to keep the original intact and reused on export time. If this results on the same vert count on export, then that was the cause of this behavior.

**Comment by eArmada8** [comment]
Closing this, thanks!  I've come to the conclusion that the game I'm working with uses fancy custom tangents and this is Blender's method of dealing with them.
