### ISSUE TITLE
Can't even get this to work (blender_3dmigoto.py)

### ISSUE THREAD

**Issue by BeeLy1011** [DarkStarSword/3d-fixes#7]
I've pasted this into the blender command tool, trying both 2.8 and 2.9, I've tried cmd, I've even tried making a .py file. Nothing has worked. It just comes up with indentation errors.

**Comment by BeeLy1011** [comment]
Nvm I got it in, but now it's giving me this: 
![ApplicationFrameHost_2021-03-18_22-05-35](https://user-images.githubusercontent.com/80932516/111734810-1235e480-8838-11eb-9065-b1b346a4c2a4.png)

**Comment by DarkStarSword** [comment]
![image](https://user-images.githubusercontent.com/379749/111735227-c46cbb00-88cf-11eb-9a49-82b4fa330c1e.png)
![image](https://user-images.githubusercontent.com/379749/111735245-d2224080-88cf-11eb-91a3-f8be50270b90.png)
![image](https://user-images.githubusercontent.com/379749/111735262-dc443f00-88cf-11eb-9e8a-b26f27c0ac98.png)
![image](https://user-images.githubusercontent.com/379749/111735276-e108f300-88cf-11eb-8dad-9092fdccdbc3.png)
![image](https://user-images.githubusercontent.com/379749/111735288-e5351080-88cf-11eb-8126-5158d0f7e81b.png)
![image](https://user-images.githubusercontent.com/379749/111735319-f1b96900-88cf-11eb-98f8-dcd39d14a3a6.png)
![image](https://user-images.githubusercontent.com/379749/111735336-f5e58680-88cf-11eb-9810-9ffa336e3501.png)

**Comment by BeeLy1011** [comment]
Thanks but I already got that part by the time you saw it, I still need to figure out what this VBStride thing is
![ApplicationFrameHost_2021-03-18_22-05-35](https://user-images.githubusercontent.com/80932516/111821006-67591100-889f-11eb-8227-7a9b266662c3.png)

**Comment by DarkStarSword** [comment]
That means you are trying to export an object that was not originally imported via the same plugin and lacks the metadata necessary to recreate the binary format from the game.

The easiest way to solve this is to join the object you want to export that lacks the metadata onto an object that was imported from the game via this plugin (select your object, shift select object imported from game, ctrl+J) so that it gains the extra metadata - you can then decide whether you want to keep the two pieces joined as one mesh, or if you still want them separate you can delete the unwanted section of the combined mesh.
